/*
 * api.video
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LiveStreamAssets
 */
public class LiveStreamAssetsTest {
    private final LiveStreamAssets model = new LiveStreamAssets();

    /**
     * Model tests for LiveStreamAssets
     */
    @Test
    public void testLiveStreamAssets() {
        // TODO: test LiveStreamAssets
    }

    /**
     * Test the property 'hls'
     */
    @Test
    public void hlsTest() {
        // TODO: test hls
    }

    /**
     * Test the property 'iframe'
     */
    @Test
    public void iframeTest() {
        // TODO: test iframe
    }

    /**
     * Test the property 'player'
     */
    @Test
    public void playerTest() {
        // TODO: test player
    }

    /**
     * Test the property 'thumbnail'
     */
    @Test
    public void thumbnailTest() {
        // TODO: test thumbnail
    }

}
