/*
 * api.video
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Collection of details about the video object that you can use to work with the video object.
 */
@ApiModel(description = "Collection of details about the video object that you can use to work with the video object.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class VideoAssets {
  public static final String SERIALIZED_NAME_HLS = "hls";
  @SerializedName(SERIALIZED_NAME_HLS)
  private URI hls;

  public static final String SERIALIZED_NAME_IFRAME = "iframe";
  @SerializedName(SERIALIZED_NAME_IFRAME)
  private String iframe;

  public static final String SERIALIZED_NAME_PLAYER = "player";
  @SerializedName(SERIALIZED_NAME_PLAYER)
  private URI player;

  public static final String SERIALIZED_NAME_THUMBNAIL = "thumbnail";
  @SerializedName(SERIALIZED_NAME_THUMBNAIL)
  private URI thumbnail;

  public static final String SERIALIZED_NAME_MP4 = "mp4";
  @SerializedName(SERIALIZED_NAME_MP4)
  private URI mp4;

  public VideoAssets() {
  }

  public VideoAssets hls(URI hls) {
    
    
    
    
    this.hls = hls;
    return this;
  }

   /**
   * This is the manifest URL. For HTTP Live Streaming (HLS), when a HLS video stream is initiated, the first file to download is the manifest. This file has the extension M3U8, and provides the video player with information about the various bitrates available for streaming.
   * @return hls
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "This is the manifest URL. For HTTP Live Streaming (HLS), when a HLS video stream is initiated, the first file to download is the manifest. This file has the extension M3U8, and provides the video player with information about the various bitrates available for streaming.")

  public URI getHls() {
    return hls;
  }


  public void setHls(URI hls) {
    
    
    
    this.hls = hls;
  }


  public VideoAssets iframe(String iframe) {
    
    
    
    
    this.iframe = iframe;
    return this;
  }

   /**
   * Code to use video from a third party website
   * @return iframe
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "<iframe src=\"//embed.api.video/c188ed58-3403-46a2-b91b-44603d10b2c9?token=831a9bd9-9f50-464c-a369-8e9d914371ae\" width=\"100%\" height=\"100%\" frameborder=\"0\" scrolling=\"no\" allowfullscreen=\"\"></iframe>", value = "Code to use video from a third party website")

  public String getIframe() {
    return iframe;
  }


  public void setIframe(String iframe) {
    
    
    
    this.iframe = iframe;
  }


  public VideoAssets player(URI player) {
    
    
    
    
    this.player = player;
    return this;
  }

   /**
   * Raw url of the player.
   * @return player
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://embed.api.video/1b9d6ae8-8f57-4b6d-8552-d636926b4f5f?token=831a9bd9-9f50-464c-a369-8e9d914371ae", value = "Raw url of the player.")

  public URI getPlayer() {
    return player;
  }


  public void setPlayer(URI player) {
    
    
    
    this.player = player;
  }


  public VideoAssets thumbnail(URI thumbnail) {
    
    
    
    
    this.thumbnail = thumbnail;
    return this;
  }

   /**
   * Poster of the video.
   * @return thumbnail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://cdn.api.video/stream/831a9bd9-9f50-464c-a369-8e9d914371ae/thumbnail.jpg", value = "Poster of the video.")

  public URI getThumbnail() {
    return thumbnail;
  }


  public void setThumbnail(URI thumbnail) {
    
    
    
    this.thumbnail = thumbnail;
  }


  public VideoAssets mp4(URI mp4) {
    
    
    
    
    this.mp4 = mp4;
    return this;
  }

   /**
   * Available only if mp4Support is enabled. Raw mp4 url.
   * @return mp4
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://cdn.api.video/vod/vi4k0jvEUuaTdRAEjQ4Jfrgz/token/8fd70443-d9f0-45d2-b01c-12c8cfc707c9/mp4/source.mp4", value = "Available only if mp4Support is enabled. Raw mp4 url.")

  public URI getMp4() {
    return mp4;
  }


  public void setMp4(URI mp4) {
    
    
    
    this.mp4 = mp4;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the VideoAssets instance itself
   */
  public VideoAssets putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VideoAssets videoAssets = (VideoAssets) o;
    return Objects.equals(this.hls, videoAssets.hls) &&
        Objects.equals(this.iframe, videoAssets.iframe) &&
        Objects.equals(this.player, videoAssets.player) &&
        Objects.equals(this.thumbnail, videoAssets.thumbnail) &&
        Objects.equals(this.mp4, videoAssets.mp4)&&
        Objects.equals(this.additionalProperties, videoAssets.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hls, iframe, player, thumbnail, mp4, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VideoAssets {\n");
    sb.append("    hls: ").append(toIndentedString(hls)).append("\n");
    sb.append("    iframe: ").append(toIndentedString(iframe)).append("\n");
    sb.append("    player: ").append(toIndentedString(player)).append("\n");
    sb.append("    thumbnail: ").append(toIndentedString(thumbnail)).append("\n");
    sb.append("    mp4: ").append(toIndentedString(mp4)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("hls");
    openapiFields.add("iframe");
    openapiFields.add("player");
    openapiFields.add("thumbnail");
    openapiFields.add("mp4");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to VideoAssets
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!VideoAssets.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in VideoAssets is not found in the empty JSON string", VideoAssets.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("hls") != null && !jsonObj.get("hls").isJsonNull()) && !jsonObj.get("hls").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hls` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hls").toString()));
      }
      if ((jsonObj.get("iframe") != null && !jsonObj.get("iframe").isJsonNull()) && !jsonObj.get("iframe").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `iframe` to be a primitive type in the JSON string but got `%s`", jsonObj.get("iframe").toString()));
      }
      if ((jsonObj.get("player") != null && !jsonObj.get("player").isJsonNull()) && !jsonObj.get("player").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `player` to be a primitive type in the JSON string but got `%s`", jsonObj.get("player").toString()));
      }
      if ((jsonObj.get("thumbnail") != null && !jsonObj.get("thumbnail").isJsonNull()) && !jsonObj.get("thumbnail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `thumbnail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("thumbnail").toString()));
      }
      if ((jsonObj.get("mp4") != null && !jsonObj.get("mp4").isJsonNull()) && !jsonObj.get("mp4").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mp4` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mp4").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VideoAssets.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VideoAssets' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VideoAssets> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VideoAssets.class));

       return (TypeAdapter<T>) new TypeAdapter<VideoAssets>() {
           @Override
           public void write(JsonWriter out, VideoAssets value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public VideoAssets read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             VideoAssets instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of VideoAssets given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of VideoAssets
  * @throws IOException if the JSON string is invalid with respect to VideoAssets
  */
  public static VideoAssets fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VideoAssets.class);
  }

 /**
  * Convert an instance of VideoAssets to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

